In [8]:
import numpy as np

In [10]:
np.empty((2,3,2))

array([[[7.79991972e-312, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 2.42336543e-057]],

       [[4.96219200e-090, 4.66818883e-062],
        [1.55196439e+184, 6.28313633e-038],
        [3.99910963e+252, 3.34957755e-061]]])

In [13]:
import random

In [11]:
names = np.array(['bob','joe','will','bob','will','joe','joe'])

In [15]:
data=np.random.randn(7,4)

In [16]:
data

array([[ 1.66654829,  0.73472762, -0.19601693, -0.12564407],
       [-0.1916476 , -2.42807953, -1.28060487,  0.4057818 ],
       [ 1.86108962,  1.14714514,  0.69671195,  2.17702778],
       [ 1.23617048,  1.72692444, -0.99648987, -0.24999781],
       [ 0.75379127, -1.38091187,  0.62751394,  1.10174649],
       [ 0.6910705 , -0.0217182 ,  0.39591993,  0.26266708],
       [-0.49683681,  0.18197362, -0.028344  , -1.28514161]])

In [17]:
names=='bob'

array([ True, False, False,  True, False, False, False])

In [18]:
data[names=='bob']

array([[ 1.66654829,  0.73472762, -0.19601693, -0.12564407],
       [ 1.23617048,  1.72692444, -0.99648987, -0.24999781]])