In [24]:
from __future__ import print_function
import torch

In [25]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.5695e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [26]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3866, 0.9396, 0.6519],
        [0.7638, 0.1934, 0.9064],
        [0.7887, 0.3762, 0.0532],
        [0.0203, 0.7620, 0.1582],
        [0.1123, 0.4626, 0.3700]])


In [27]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [28]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [29]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)      

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.3082, -0.0425, -1.1604],
        [ 1.0512, -0.3528,  0.3298],
        [ 0.7960,  0.7996,  0.3661],
        [ 2.2413,  0.1344,  1.8088],
        [ 0.5283, -1.2747, -0.4193]])


In [30]:
print(x.size())

torch.Size([5, 3])


In [32]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.4135,  0.7285, -0.4429],
        [ 1.4020, -0.2994,  0.7659],
        [ 1.1500,  1.0782,  1.3234],
        [ 2.3353,  0.5657,  1.8535],
        [ 0.7421, -0.8547,  0.3294]])


In [33]:
print(torch.add(x, y))

tensor([[-0.4135,  0.7285, -0.4429],
        [ 1.4020, -0.2994,  0.7659],
        [ 1.1500,  1.0782,  1.3234],
        [ 2.3353,  0.5657,  1.8535],
        [ 0.7421, -0.8547,  0.3294]])


In [34]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.4135,  0.7285, -0.4429],
        [ 1.4020, -0.2994,  0.7659],
        [ 1.1500,  1.0782,  1.3234],
        [ 2.3353,  0.5657,  1.8535],
        [ 0.7421, -0.8547,  0.3294]])


In [35]:
y.add_(x)
print(y)

tensor([[-0.4135,  0.7285, -0.4429],
        [ 1.4020, -0.2994,  0.7659],
        [ 1.1500,  1.0782,  1.3234],
        [ 2.3353,  0.5657,  1.8535],
        [ 0.7421, -0.8547,  0.3294]])
